spring:
  application:
    name: microservice02
  profiles:
    default: default
  kafka:
    producer:
      properties:
        enable:
          idempotent: true
      bootstrap-servers: ${BROKER_URL}
    consumer:
      auto-offset-reset: earliest
      group-id: group-2
      retries: 100
      properties:
        enable:
          idempotent: true
      bootstrap-servers: ${BROKER_URL}
server:
  servlet:
    context-path: /microservice02
  port: 8084
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
kafka:
  topic: microservice05
  processed-topic: microservice02